# Generated by Django 3.0.5 on 2020-11-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=30)),
                ('feedback_email', models.EmailField(max_length=100)),
                ('feedback_content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_user_name', models.CharField(max_length=100)),
                ('video_email', models.EmailField(max_length=100)),
                ('video_title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('video_article', models.FileField(upload_to='article/')),
            ],
        ),
    ]
