# Generated by Django 3.0.5 on 2020-11-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_user_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
