# Generated by Django 3.0.5 on 2020-11-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0002_auto_20201125_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_article',
            field=models.FileField(upload_to='article'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos'),
        ),
    ]
