# Generated by Django 3.0.5 on 2020-11-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0003_auto_20201125_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_content',
            field=models.TextField(max_length=1000, verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_article',
            field=models.FileField(upload_to='article', verbose_name='upload Article'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos', verbose_name='upload Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(max_length=100, verbose_name='video Title'),
        ),
    ]
